### ISSUE TITLE
Clarification regarding tests (Just Asking)

### ISSUE THREAD

**Issue by azizhk** [sindresorhus/typescript-definition-style-guide#4]
So the example mentioned for [delay](https://github.com/sindresorhus/delay) are perfect because delay has a conditional return type depending on the type of value.

But would you want tests for constant types.
Like for example [clone-regexp](https://github.com/sindresorhus/clone-regexp) always returns a regexp.

It sounds like overkill because if it does not return a regexp it is not the types test which would fail, but the function itself.

Or you prefer the files and test setup created so that if any complexity gets added its easier for the next person to update tests as well.

**Comment by SamVerschueren** [comment]
Adding a test which does something like `expectType<RegExp>(cloneRegexp(/[a-z]/gi));` will verify that the type definition is written correctly. If someone in the future, in a PR or something, changes the return type from `RegExp` to `string` or `void` or whatever, the automated tests will catch it. 

It makes sure that if you change something, you know what you are doing because you can't just change something without changing the tests as well and think again what you are doing is actually correct.

**Comment by sindresorhus** [comment]
What Sam said. It's easy to think that something has constant types, and then the module is refactored or expands and by accident it slightly changes the type. Not likely to happen in that specific module, but it has and can easily happen.

**Comment by azizhk** [comment]
Ok got it. If you are improving something lay a good foundation.
