### ISSUE TITLE
Replace textual guidelines with ESLint rules where possible

### ISSUE THREAD

**Issue by fregante** [sindresorhus/typescript-definition-style-guide#6]
Instead of a 590-words styleguide it could be shorter and the rest can be enforced by eslint, where automation is possible, like:

- Use tab-indentation and semicolons.
- Don't prefix the name of interfaces with `I`; `Options`, not `IOptions`: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/interface-name-prefix.md
- Imports, destructuring, and object literals should *not* have spaces around the identifier; `{foo}`, not `{ foo }`.
- Use the array shorthand type notation; number[], not Array<number>. https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-array-constructor.md

**Comment by sindresorhus** [comment]
This has always been the goal. I just needed something immediate as automation will take time.

This is mostly blocked by https://github.com/xojs/xo/issues/373. The intention is for XO to lint ambient files (`index.d.ts`) by default.

I'm also holding out for `typescript-eslint` to be more mature. I don't want to have to disable rules in hundreds of modules because of `typescript-eslint` bugs. It's also missing a *lot* of needed rules.

**Comment by sindresorhus** [comment]
If anyone wants to help out. Find things in the style guide that can be automated, check if `typescript-eslint` has a rule for it, if yes, comment it here, if not, open a rule request on `typescript-eslint` and comment the issue link here.

**Comment by fregante** [comment]
I noticed Airbnb actually still has the [verbal styleguide](https://github.com/airbnb/javascript) _in addition_ to the shareable config. Not something I'd personally read, but perhaps some people do.
